#!/bin/sh
#PBS -N jobname
#PBS -l nodes=1:ppn=32:debug
#PBS -l walltime=02:00:00

cd /home/mas/14/secsat/se295/ass1/1 
NPROCS=`wc -l < $PBS_NODEFILE`
HOSTS=`cat $PBS_NODEFILE | uniq | tr '\n' "," | sed 's|,$||'`
mpirun -np 1 ./q1.out> result1


