#!/bin/sh
#PBS -l nodes=1:ppn=1:gpus=1
#PBS -o /home/mas/14/secsat/se295/ass1/cuda/output.log
setenv CUDA_PROFILE 1
setenv CUDA_PROFILE_CSV 1
setenv CUDA_PROFILE_LOG /home/mas/14/secsat/se295/ass1/cuda/matvec.csv
setenv CUDA_PROFILE_CONFIG /home/mas/14/secsat/se295/ass1/cuda/config.txt
/home/mas/14/secsat/se295/ass1/cuda/bout > /home/mas/14/secsat/se295/ass1/cuda/output.log

