#!/bin/sh
#PBS -N SKP
#PBS -l nodes=1:ppn=16:debug
#PBS -l walltime=02:00:00

cd /home/mas/14/secsat/se295/ass2 
NPROCS=`wc -l < $PBS_NODEFILE`
HOSTS=`cat $PBS_NODEFILE | uniq | tr '\n' "," | sed 's|,$||'`
mpirun -np 16 ./q1.out> result1

